name: CodeGuru Reviewer

on:
  pull_request:

jobs:
  codeguru-review:
    name: Run CodeGuru Reviewer
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::992382635843:role/codeguru
          aws-region: us-east-1  # o tu región preferida

      - name: CodeGuru Reviewer scan
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: codeguru-reviewer-my-bucket  # debe empezar con "codeguru-reviewer-"
          # Si tu código es Java compilado, descomenta la siguiente línea:
          # build_path: target

      - name: Upload SARIF results (optional)
        if: ${{ github.event_name != 'push' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json

